FROM montereytony/ugba147:summer-2023-tree1-nb7
USER root
RUN  apt-get update && apt-get install -y \
	apt-transport-https \
	ca-certificates \
	curl \
	gnupg \
	hicolor-icon-theme \
	libcanberra-gtk* \
	libgl1-mesa-dri \
	libgl1-mesa-glx \
	libpango1.0-0 \
	libpulse0 \
	libv4l-0 \
        r-cran-rgl \
        freeglut3-dev \
        libglu1-mesa-dev freeglut3-dev mesa-common-dev \
	fonts-symbola \
	--no-install-recommends \
	&& curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
	&& echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list \
	&& apt-get update && apt-get install -y \
	--no-install-recommends \
	google-chrome-stable \
	&& apt-get purge --auto-remove -y curl \
	&& rm -rf /var/lib/apt/lists/*
RUN pip install jupyter_contrib_nbextensions && jupyter contrib nbextension install 
RUN wget https://downloads.vivaldi.com/stable/vivaldi-stable_5.5.2805.35-1_amd64.deb 
RUN apt-get update && apt-get install -y ./vivaldi-stable_5.5.2805.35-1_amd64.deb && rm -rf /var/lib/apt/lists/*
RUN echo CHROMOTE_CHROME=/usr/bin/vivaldi >> .Renviron
