#
# Start with minimal image
#
ARG BASE_CONTAINER=jupyter/minimal-notebook
FROM $BASE_CONTAINER
#
# Take ownership of the mess to follow
#
ARG OWNER=montereytony@gmail.com

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
USER root
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV DEBIAN_FRONTEND noninteractive
RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen &&\
	locale-gen en_US.utf8 && \
	/usr/sbin/update-locale  LANG=en_US.UTF-8


RUN apt update && sudo apt -y  dist-upgrade && \
    apt-get update --yes && \
    apt-get install --yes --no-install-recommends \
    software-properties-common \
    build-essential \
    fonts-dejavu \
    unixodbc \
    unixodbc-dev \
    r-cran-rodbc \
    gfortran \
    gcc \
    pkg-config \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    hicolor-icon-theme \
    libcanberra-gtk* \
    libgl1-mesa-dri \
    libgl1-mesa-glx \
    libpango1.0-0 \
    libpulse0 \
    libv4l-0 \
    zlib1g-dev zlib1g \
    r-cran-rgl \
    freeglut3-dev \
    libglu1-mesa-dev freeglut3-dev mesa-common-dev \
    fonts-symbola \
    --no-install-recommends \
    && curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list \
    && apt-get update && apt-get install -y \
    --no-install-recommends \
    google-chrome-stable  &&\
    wget https://downloads.vivaldi.com/stable/vivaldi-stable_5.5.2805.35-1_amd64.deb  &&\
    apt-get update && apt-get install -y ./vivaldi-stable_5.5.2805.35-1_amd64.deb && rm -rf /var/lib/apt/lists/* && \
    echo CHROMOTE_CHROME=/usr/bin/vivaldi >> .Renviron && \
    apt-get purge --auto-remove -y curl && \
    rm -rf /var/lib/apt/lists/*


USER ${NB_UID}

#
# Prof Huntsinger asked for R 4.2.2
#
ENV R_BASE_VERSION 4.2.2

RUN conda update -n base -c defaults conda && \
    mamba install --yes \
    r-base=${R_BASE_VERSION} \
    'r-caret' \
    'r-crayon' \
    'r-devtools' \
    'r-e1071' \
    'r-forecast' \
    'r-hexbin' \
    'r-htmltools' \
    'r-htmlwidgets' \
    'r-irkernel' \
    'r-nycflights13' \
    'r-randomforest' \
    'r-rcurl' \
    'r-rmarkdown' \
    'r-rodbc' \
    'r-rsqlite' \
    'r-shiny' \
    'r-tidymodels' \
    'r-tidyverse' \
    'gcc_linux-64' \
    'gfortran_linux-64' \
    'r-essentials' \
    'r-htmlwidgets' \
    'r-gridExtra' \
    'r-e1071' \
    'r-rgl' \
    'r-xlsxjars' \
    'r-xlsx' \
    'r-aer ' \
    'r-png' \
    'r-rJava' \
    'r-devtools' \
    'r-digest' \
    'r-evaluate' \
    'r-memoise ' \
    'r-withr ' \
    'r-irdisplay' \
    'r-r6 ' \
    'r-base' \
    'r-lightgbm' \
    'r-plyr' \
    'r-dplyr' \
    'r-base64enc' \
    'r-caret' \
    'r-colorspace' \
    'r-e1071' \
    'r-entropy' \
    'r-fastDummies' \
    'r-ggdendro' \
    'r-GGally' \
    'r-ggplot2' \
    'r-gtools' \
    'r-ggwordcloud' \
    'r-gridExtra' \
    'r-htmltools' \
    'r-igraph' \
    'r-IRdisplay' \
    'r-kableExtra' \
    'r-kknn' \
    'r-ks' \
    'r-knitr' \
    'r-lubridate' \
    'r-MASS' \
    'r-mclust' \
    'r-mvtnorm' \
    'r-neuralnet' \
    'r-NLP' \
    'r-OpenImageR' \
    'r-pracma' \
    'r-polyclip' \
    'r-psych' \
    'r-qgraph' \
    'r-readxl' \
    'r-reshape2' \
    'r-rjson' \
    'r-rmarkdown' \
    'r-rpart' \
    'r-rpart.plot' \
    'r-stringr' \
    'r-SnowballC' \
    'r-tm' \
    'r-writexl'  \
    'numpy'\
    'statsmodels' \
    'r-webshot2' \
    'r-imager' \
    'r-rgl' \
    'unixodbc' 

RUN mamba install -c conda-forge r-webshot  uwsgi jupyter_contrib_nbextensions 
RUN mamba install -c r r-simmer r-remotes r-stringi  nbgrader nbgitpuller r-ggnewscale
RUN Rscript -e 'remotes::install_github("ShotaOchi/imagerExtra")' && \
    Rscript -e 'remotes::install_github("r-simmer/simmer.plot")'
USER root
COPY custom.css          /tmp
COPY common.json         /tmp
COPY tree.json           /tmp
COPY notebook.json       /tmp
COPY common.json         /tmp
COPY tree.json           /tmp
COPY notebook.json       /tmp
COPY add_files.sh        /tmp
COPY fixer.sh /tmp
COPY fix-permissions /tmp
RUN mamba clean --all -f -y && \
    bash /tmp/fixer.sh && \
    chmod -R 775 "${CONDA_DIR}" && \
    chown -R ${NB_USER} "${CONDA_DIR}" && \
    chown -R ${NB_USER} "/home/${NB_USER}" &&\
    bash /tmp/add_files.sh  &&\
    bash /tmp/fix-permissions  
USER ${NB_UID}
RUN jupyter labextension install @jupyterlab/hub-extension && \
    jupyter nbextensions_configurator enable --sys-prefix  && \
    jupyter labextension enable --level=system nbgrader   && \
    jupyter server extension enable --system --py nbgrader && \
    jupyter nbextension install --py widgetsnbextension --sys-prefix && \
    jupyter nbextension enable  --py widgetsnbextension --sys-prefix && \
    jupyter-nbextension install rise --py --sys-prefix  && \
    jupyter-nbextension enable  rise --py --sys-prefix
    jupyter contrib nbextension install --user &&\
    jupyter nbextension install --py widgetsnbextension --sys-prefix && \
    jupyter nbextension enable  --py widgetsnbextension --sys-prefix && \
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$JAVA_LD_LIBRARY_PATH
RUN pip install jupyterthemes  && \
    pip install --upgrade jupyterthemes  && \
    pip install jupyter_contrib_nbextensions  && \
    pip install RISE  && \
